services:
  mysql:
    image: mysql:8.0
    container_name: gas_station_mysql
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - '${DB_PORT}:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 20s
      retries: 10

volumes:
  mysql_data:
    driver: local
