/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AssociateLeadSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'ilevaAssociateId', 'ilevaLeadId', 'name', 'phone', 'updatedAt', 'userId'] as const
  $columns = AssociateLeadSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare ilevaAssociateId: number | null
  @column()
  declare ilevaLeadId: number | null
  @column()
  declare name: string | null
  @column()
  declare phone: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
}

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ConsultationSchema extends BaseModel {
  static $columns = ['consultedBy', 'createdAt', 'fuelPumpVisorImage', 'gasStationId', 'id', 'ilevaVehicleId', 'licensePlate', 'partner', 'updatedAt', 'userId', 'vehicleSituation', 'wasRefueled'] as const
  $columns = ConsultationSchema.$columns
  @column()
  declare consultedBy: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare fuelPumpVisorImage: string | null
  @column()
  declare gasStationId: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare ilevaVehicleId: number | null
  @column()
  declare licensePlate: string
  @column()
  declare partner: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
  @column()
  declare vehicleSituation: string
  @column({ consume: (value) => (value === null ? null : Boolean(value)) })
  declare wasRefueled: boolean | null
}

export class FuelSuplyCancellationSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'plate', 'reason', 'updatedAt', 'userId'] as const
  $columns = FuelSuplyCancellationSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare plate: string
  @column()
  declare reason: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
}

export class GasStationSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'name', 'updatedAt'] as const
  $columns = GasStationSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class LeadSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'ilevaAssociateId', 'name', 'partner', 'phone', 'updatedAt'] as const
  $columns = LeadSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare ilevaAssociateId: number | null
  @column()
  declare name: string | null
  @column()
  declare partner: string | null
  @column()
  declare phone: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserFaceImageSchema extends BaseModel {
  static $columns = ['createdAt', 'faceDescriptor', 'id', 'imagePath', 'updatedAt', 'userId'] as const
  $columns = UserFaceImageSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare faceDescriptor: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare imagePath: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'gasStationId', 'id', 'password', 'role', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column()
  declare gasStationId: number | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare role: 'attendant' | 'manager' | 'admin'
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class VouncherUtilizationSchema extends BaseModel {
  static $columns = ['cpf', 'createdAt', 'id', 'licensePlate', 'name', 'phone', 'updatedAt', 'vouncherId'] as const
  $columns = VouncherUtilizationSchema.$columns
  @column()
  declare cpf: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare licensePlate: string
  @column()
  declare name: string
  @column()
  declare phone: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare vouncherId: number
}

export class VouncherSchema extends BaseModel {
  static $columns = ['code', 'createdAt', 'createdBy', 'currentUtilizations', 'dieselPrice', 'ethanolPrice', 'expiresAt', 'gasolinePrice', 'id', 'isActive', 'maxUtilizations', 'partner', 'type', 'updatedAt'] as const
  $columns = VouncherSchema.$columns
  @column()
  declare code: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare createdBy: number | null
  @column()
  declare currentUtilizations: number
  @column({ consume: (value) => (value === null ? null : Number(value)) })
  declare dieselPrice: number
  @column({ consume: (value) => (value === null ? null : Number(value)) })
  declare ethanolPrice: number
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ consume: (value) => (value === null ? null : Number(value)) })
  declare gasolinePrice: number
  @column({ isPrimary: true })
  declare id: number
  @column({ consume: (value) => (value === null ? null : Boolean(value)) })
  declare isActive: boolean
  @column()
  declare maxUtilizations: number
  @column()
  declare partner: string | null
  @column()
  declare type: 'operational' | 'commercial' | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
