/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class ConsultationSchema extends BaseModel {
  static $columns = ['consultedBy', 'createdAt', 'fuelPumpVisorImage', 'id', 'ilevaVehicleId', 'licensePlate', 'partner', 'updatedAt', 'vehicleSituation', 'wasRefueled'] as const
  $columns = ConsultationSchema.$columns
  @column()
  declare consultedBy: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare fuelPumpVisorImage: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare ilevaVehicleId: number | null
  @column()
  declare licensePlate: string
  @column()
  declare partner: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare vehicleSituation: string
  @column({ consume: (value) => (value === null ? null : Boolean(value)) })
  declare wasRefueled: boolean | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class VouncherUtilizationSchema extends BaseModel {
  static $columns = ['cpf', 'createdAt', 'id', 'licensePlate', 'name', 'phone', 'updatedAt', 'vouncherId'] as const
  $columns = VouncherUtilizationSchema.$columns
  @column()
  declare cpf: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare licensePlate: string
  @column()
  declare name: string
  @column()
  declare phone: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare vouncherId: number
}

export class VouncherSchema extends BaseModel {
  static $columns = ['code', 'createdAt', 'createdBy', 'currentUtilizations', 'dieselPrice', 'ethanolPrice', 'expiresAt', 'gasolinePrice', 'id', 'isActive', 'maxUtilizations', 'partner', 'type', 'updatedAt'] as const
  $columns = VouncherSchema.$columns
  @column()
  declare code: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare createdBy: number | null
  @column()
  declare currentUtilizations: number
  @column({ consume: (value) => (value === null ? null : Number(value)) })
  declare dieselPrice: number
  @column({ consume: (value) => (value === null ? null : Number(value)) })
  declare ethanolPrice: number
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ consume: (value) => (value === null ? null : Number(value)) })
  declare gasolinePrice: number
  @column({ isPrimary: true })
  declare id: number
  @column({ consume: (value) => (value === null ? null : Boolean(value)) })
  declare isActive: boolean
  @column()
  declare maxUtilizations: number
  @column()
  declare partner: string | null
  @column()
  declare type: 'operational' | 'commercial' | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
