/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="../../adonisrc.ts" />
/// <reference path="../../config/auth.ts" />
/// <reference path="../../config/drive.ts" />
/// <reference path="../../config/evolution.ts" />
/// <reference path="../../config/ezchat.ts" />
/// <reference path="../../config/face_recognition.ts" />
/// <reference path="../../config/hash.ts" />
/// <reference path="../../config/logger.ts" />
/// <reference path="../../config/solidy.ts" />
